import NavigationBar from "@/components/navbar";
import "@/styles/globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import '@/styles/custom.css';

import { type Metadata } from "next";
import { Open_Sans} from "next/font/google"
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

//fonts
const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet"/>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet"/>
      {/* Libraries Stylesheet  */}
    <link href="/lib/animate/animate.min.css" rel="stylesheet"/>
    <link href="/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet"/>
    

      </head>
      <body className={openSans.className}>
        <NavigationBar></NavigationBar>
        {children}
        <Footer/>
        {/* <!-- JavaScript Libraries --> */}
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="/lib/wow/wow.min.js"></script>
    <script src="/lib/easing/easing.min.js"></script>
    <script src="/lib/waypoints/waypoints.min.js"></script>
    <script src="/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="/lib/counterup/counterup.min.js"></script>

    {/* <!-- Template Javascript --> */}
    <script src="js/main.js"></script>
        </body>

    </html>
  );
}
