import NavigationBar from "@/components/navbar";
import "@/styles/globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import '@/styles/custom.css';

import { type Metadata } from "next";
import { Open_Sans} from "next/font/google"
import Footer from "@/components/footer";
import Script from 'next/script';

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

//fonts
const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Libraries Stylesheet */}
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet"/>
      </head>
      <body className={openSans.className}>
        <NavigationBar></NavigationBar>
        {children}
        <Footer/>
        {/* JavaScript Libraries */}
        <Script src="https://code.jquery.com/jquery-3.4.1.min.js" strategy="lazyOnload" />
        <Script src="/lib/wow/wow.min.js" strategy="lazyOnload" />
        <Script src="/lib/easing/easing.min.js" strategy="lazyOnload" />
        <Script src="/lib/waypoints/waypoints.min.js" strategy="lazyOnload" />
        <Script src="/lib/owlcarousel/owl.carousel.min.js" strategy="lazyOnload" />
        <Script src="/lib/counterup/counterup.min.js" strategy="lazyOnload" />
        {/* Template Javascript */}
        <Script src="js/main.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
